// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageServantStateReply.proto

#ifndef PROTOBUF_MessageServantStateReply_2eproto__INCLUDED
#define PROTOBUF_MessageServantStateReply_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageServantStateReply_2eproto();
void protobuf_AssignDesc_MessageServantStateReply_2eproto();
void protobuf_ShutdownFile_MessageServantStateReply_2eproto();

class MessageServantStateReply;

// ===================================================================

class MessageServantStateReply : public ::google::protobuf::Message {
 public:
  MessageServantStateReply();
  virtual ~MessageServantStateReply();

  MessageServantStateReply(const MessageServantStateReply& from);

  inline MessageServantStateReply& operator=(const MessageServantStateReply& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageServantStateReply& default_instance();

  void Swap(MessageServantStateReply* other);

  // implements Message ----------------------------------------------

  MessageServantStateReply* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageServantStateReply& from);
  void MergeFrom(const MessageServantStateReply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string id = 1;
  inline int id_size() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline const ::std::string& id(int index) const;
  inline ::std::string* mutable_id(int index);
  inline void set_id(int index, const ::std::string& value);
  inline void set_id(int index, const char* value);
  inline void set_id(int index, const char* value, size_t size);
  inline ::std::string* add_id();
  inline void add_id(const ::std::string& value);
  inline void add_id(const char* value);
  inline void add_id(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& id() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_id();

  // repeated int32 state = 2;
  inline int state_size() const;
  inline void clear_state();
  static const int kStateFieldNumber = 2;
  inline ::google::protobuf::int32 state(int index) const;
  inline void set_state(int index, ::google::protobuf::int32 value);
  inline void add_state(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      state() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_state();

  // repeated int32 cpu = 3;
  inline int cpu_size() const;
  inline void clear_cpu();
  static const int kCpuFieldNumber = 3;
  inline ::google::protobuf::int32 cpu(int index) const;
  inline void set_cpu(int index, ::google::protobuf::int32 value);
  inline void add_cpu(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      cpu() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_cpu();

  // repeated int32 memory = 4;
  inline int memory_size() const;
  inline void clear_memory();
  static const int kMemoryFieldNumber = 4;
  inline ::google::protobuf::int32 memory(int index) const;
  inline void set_memory(int index, ::google::protobuf::int32 value);
  inline void add_memory(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      memory() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_memory();

  // repeated int32 type = 5;
  inline int type_size() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 5;
  inline ::google::protobuf::int32 type(int index) const;
  inline void set_type(int index, ::google::protobuf::int32 value);
  inline void add_type(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      type() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_type();

  // @@protoc_insertion_point(class_scope:MessageServantStateReply)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> id_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > state_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > cpu_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > memory_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > type_;
  friend void  protobuf_AddDesc_MessageServantStateReply_2eproto();
  friend void protobuf_AssignDesc_MessageServantStateReply_2eproto();
  friend void protobuf_ShutdownFile_MessageServantStateReply_2eproto();

  void InitAsDefaultInstance();
  static MessageServantStateReply* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageServantStateReply

// repeated string id = 1;
inline int MessageServantStateReply::id_size() const {
  return id_.size();
}
inline void MessageServantStateReply::clear_id() {
  id_.Clear();
}
inline const ::std::string& MessageServantStateReply::id(int index) const {
  // @@protoc_insertion_point(field_get:MessageServantStateReply.id)
  return id_.Get(index);
}
inline ::std::string* MessageServantStateReply::mutable_id(int index) {
  // @@protoc_insertion_point(field_mutable:MessageServantStateReply.id)
  return id_.Mutable(index);
}
inline void MessageServantStateReply::set_id(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:MessageServantStateReply.id)
  id_.Mutable(index)->assign(value);
}
inline void MessageServantStateReply::set_id(int index, const char* value) {
  id_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageServantStateReply.id)
}
inline void MessageServantStateReply::set_id(int index, const char* value, size_t size) {
  id_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageServantStateReply.id)
}
inline ::std::string* MessageServantStateReply::add_id() {
  return id_.Add();
}
inline void MessageServantStateReply::add_id(const ::std::string& value) {
  id_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:MessageServantStateReply.id)
}
inline void MessageServantStateReply::add_id(const char* value) {
  id_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:MessageServantStateReply.id)
}
inline void MessageServantStateReply::add_id(const char* value, size_t size) {
  id_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:MessageServantStateReply.id)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MessageServantStateReply::id() const {
  // @@protoc_insertion_point(field_list:MessageServantStateReply.id)
  return id_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MessageServantStateReply::mutable_id() {
  // @@protoc_insertion_point(field_mutable_list:MessageServantStateReply.id)
  return &id_;
}

// repeated int32 state = 2;
inline int MessageServantStateReply::state_size() const {
  return state_.size();
}
inline void MessageServantStateReply::clear_state() {
  state_.Clear();
}
inline ::google::protobuf::int32 MessageServantStateReply::state(int index) const {
  // @@protoc_insertion_point(field_get:MessageServantStateReply.state)
  return state_.Get(index);
}
inline void MessageServantStateReply::set_state(int index, ::google::protobuf::int32 value) {
  state_.Set(index, value);
  // @@protoc_insertion_point(field_set:MessageServantStateReply.state)
}
inline void MessageServantStateReply::add_state(::google::protobuf::int32 value) {
  state_.Add(value);
  // @@protoc_insertion_point(field_add:MessageServantStateReply.state)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
MessageServantStateReply::state() const {
  // @@protoc_insertion_point(field_list:MessageServantStateReply.state)
  return state_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
MessageServantStateReply::mutable_state() {
  // @@protoc_insertion_point(field_mutable_list:MessageServantStateReply.state)
  return &state_;
}

// repeated int32 cpu = 3;
inline int MessageServantStateReply::cpu_size() const {
  return cpu_.size();
}
inline void MessageServantStateReply::clear_cpu() {
  cpu_.Clear();
}
inline ::google::protobuf::int32 MessageServantStateReply::cpu(int index) const {
  // @@protoc_insertion_point(field_get:MessageServantStateReply.cpu)
  return cpu_.Get(index);
}
inline void MessageServantStateReply::set_cpu(int index, ::google::protobuf::int32 value) {
  cpu_.Set(index, value);
  // @@protoc_insertion_point(field_set:MessageServantStateReply.cpu)
}
inline void MessageServantStateReply::add_cpu(::google::protobuf::int32 value) {
  cpu_.Add(value);
  // @@protoc_insertion_point(field_add:MessageServantStateReply.cpu)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
MessageServantStateReply::cpu() const {
  // @@protoc_insertion_point(field_list:MessageServantStateReply.cpu)
  return cpu_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
MessageServantStateReply::mutable_cpu() {
  // @@protoc_insertion_point(field_mutable_list:MessageServantStateReply.cpu)
  return &cpu_;
}

// repeated int32 memory = 4;
inline int MessageServantStateReply::memory_size() const {
  return memory_.size();
}
inline void MessageServantStateReply::clear_memory() {
  memory_.Clear();
}
inline ::google::protobuf::int32 MessageServantStateReply::memory(int index) const {
  // @@protoc_insertion_point(field_get:MessageServantStateReply.memory)
  return memory_.Get(index);
}
inline void MessageServantStateReply::set_memory(int index, ::google::protobuf::int32 value) {
  memory_.Set(index, value);
  // @@protoc_insertion_point(field_set:MessageServantStateReply.memory)
}
inline void MessageServantStateReply::add_memory(::google::protobuf::int32 value) {
  memory_.Add(value);
  // @@protoc_insertion_point(field_add:MessageServantStateReply.memory)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
MessageServantStateReply::memory() const {
  // @@protoc_insertion_point(field_list:MessageServantStateReply.memory)
  return memory_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
MessageServantStateReply::mutable_memory() {
  // @@protoc_insertion_point(field_mutable_list:MessageServantStateReply.memory)
  return &memory_;
}

// repeated int32 type = 5;
inline int MessageServantStateReply::type_size() const {
  return type_.size();
}
inline void MessageServantStateReply::clear_type() {
  type_.Clear();
}
inline ::google::protobuf::int32 MessageServantStateReply::type(int index) const {
  // @@protoc_insertion_point(field_get:MessageServantStateReply.type)
  return type_.Get(index);
}
inline void MessageServantStateReply::set_type(int index, ::google::protobuf::int32 value) {
  type_.Set(index, value);
  // @@protoc_insertion_point(field_set:MessageServantStateReply.type)
}
inline void MessageServantStateReply::add_type(::google::protobuf::int32 value) {
  type_.Add(value);
  // @@protoc_insertion_point(field_add:MessageServantStateReply.type)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
MessageServantStateReply::type() const {
  // @@protoc_insertion_point(field_list:MessageServantStateReply.type)
  return type_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
MessageServantStateReply::mutable_type() {
  // @@protoc_insertion_point(field_mutable_list:MessageServantStateReply.type)
  return &type_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageServantStateReply_2eproto__INCLUDED
